#!/usr/bin/python

vpnstatus = """
{
  "openvpn_0": {
    "client_list": [
      [
        "vpupkin", 
        "32.1.1.2:61173", 
        "10.0.0.69", 
        "", 
        "46473652", 
        "117695232", 
        "Wed Aug 18 06:30:16 2021", 
        "1629268216", 
        "vpupkin", 
        "10872", 
        "0"
      ], 
      [
        "ccyrilkin", 
        "8.8.8.9:60094", 
        "10.0.0.62", 
        "", 
        "11332614", 
        "7056514", 
        "Wed Aug 18 08:33:29 2021", 
        "1629275609", 
        "ccyrilkin", 
        "10899", 
        "0"
      ]
    ], 
    "global_stats": {
      "Max bcast/mcast queue length": "10"
    }, 
    "time": [
      "Wed Aug 18 08:49:02 2021", 
      "1629276542"
    ], 
    "title": "OpenVPN 2.4.9as2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 13 2021"
  }, 
  "openvpn_1": {
    "client_list": [
      [
        "ipupkin", 
        "17.18.19.20:51979", 
        "10.0.0.206", 
        "", 
        "14722394", 
        "12662809", 
        "Wed Aug 18 07:46:28 2021", 
        "1629272788", 
        "ipupkin", 
        "37960", 
        "119"
      ], 
      [
        "alkonost", 
        "77.7.7.7:55493", 
        "10.0.0.81", 
        "", 
        "7196204", 
        "8116344", 
        "Wed Aug 18 07:54:01 2021", 
        "1629273241", 
        "alkonost", 
        "37972", 
        "121"
      ]
    ], 
    "global_stats": {
      "Max bcast/mcast queue length": "193"
    }, 
    "time": [
      "Wed Aug 18 08:49:02 2021", 
      "1629276542"
    ], 
    "title": "OpenVPN 2.4.9as2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 13 2021"
  }
}

"""

vpnsummary = """{
    "active_profile": "Default",
    "errors": {},
    "last_restarted": "Tue Aug 17 13:11:58 2021",
    "service_status": {
      "api": "on",
      "auth": "on",
      "bridge": "on",
      "client_query": "on",
      "crl": "on",
      "daemon_pre": "on",
      "db_push": "on",
      "ip6tables_live": "on",
      "ip6tables_openvpn": "on",
      "iptables_live": "on",
      "iptables_openvpn": "on",
      "iptables_web": "on",
      "log": "on",
      "openvpn_0": "on",
      "openvpn_1": "on",
      "subscription": "on",
      "user": "on",
      "web": "on"
    }
  }
  """

subscriptionstatus = """{
	"agent_disabled": false,
	"cc_limit": 250,
	"current_cc": 168,
	"error": null,
	"fallback_cc": 2,
	"grace_period": 30,
	"last_successful_update": 1629457445,
	"last_successful_update_age": 65,
	"max_cc": 250,
	"name": "Subscription 1",
	"next_update": 1629457645,
	"next_update_in": 134,
	"notes": [],
	"overdraft": false,
	"server": "asb.sts.openvpn.net",
	"state": "SUBSCRIPTION_OK",
	"type": "-",
	"updates_failed": 0
}
"""

import sys
import os

if len(sys.argv) != 2 :
    exit()

if sys.argv[1].lower() == 'vpnstatus':
    print(vpnstatus)
elif sys.argv[1].lower() == 'subscriptionstatus':
    print(SubscriptionStatus)
elif sys.argv[1].lower() == 'vpnsummary':
    print(vpnsummary)
else:
    print("blablabla read --help")