{
 "title": "OpenVPN-AS",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(openvpnas_vpnstatus_parsed, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"openvpn-as\",instance=\"10.200.0.100:9185\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - openvpnas_status_last_restarted"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 19, "w": 3, "x": 6, "y": 0 },
   "targets": [
    { "expr": "openvpnas_status_service_state", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpnas_vpnstatus_client_bytes_received[1d]))"
    }
   ]
  },
  {
   "title": "Send",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpnas_vpnstatus_client_bytes_send[1d]))"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "table",
   "gridPos": { "h": 24, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openvpnas_vpnstatus_client_info"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openvpnas_subscription_current_cc",
     "legendFormat": "Current"
    },
    { "expr": "openvpnas_subscription_max_cc", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "Top Traffic Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpnas_vpnstatus_client_bytes_received[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Top Traffic Send",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpnas_vpnstatus_client_bytes_send[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Client Network Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(openvpnas_vpnstatus_client_bytes_received[10m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(openvpnas_vpnstatus_client_bytes_send[10m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openvpnas_status_parsed", "legendFormat": "sacli status parsed" }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort(sum(increase(openvpnas_vpnstatus_client_bytes_received[1d])+increase(openvpnas_vpnstatus_client_bytes_send[1d])) by (common_name))",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openvpnas_vpnstatus_parsed", "legendFormat": "sacli VPNStatus parsed" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpnas_subscription_parsed",
     "legendFormat": "sacli SubscriptionStatus parsed"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\".*$node:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\".*$node:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\".*$node:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\".*$node:9100\"} * 100) / node_memory_MemTotal_bytes{instance=~\".*$node:9100\"})"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\".*$node:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*$node:9100\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  }
 ]
}